version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  python: circleci/python@1.4.0
  heroku: circleci/heroku@0.0.10
jobs:
  # deliberately not doing anything in build so we can have a job called test which is what heroku workflow requires
  build:
    working_directory: ~/drink-this-backend
    docker:
      - image: cimg/ruby:2.7.2
        environment:
          PG_HOST: localhost
          PG_USER: circleci
      - image: postgres:13.3
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: drink-this-backend_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout

  test:
    docker:
      - image: cimg/ruby:2.7.2
        environment:
          PG_HOST: localhost
          PG_USER: circleci
      - image: postgres:13.3
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: drink-this-backend_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install python3 python3-dev
      - run: sudo apt-get install python3-pip
      # - run: curl https://pyenv.run | bash
      - run: pip install numpy
      - run: pip install pandas
      - run: pip install sklearn
      - run: bundle install
      - run:
          name: set up DB
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
          environment:
              DATABASE_URL: "postgres://circleci@localhost:5432/drink-this-backend_test"
      - run: bundle exec rspec spec


workflows:
  heroku_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - test
          filters:
            branches:
              only: python_config
