version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  python: circleci/python@1.4.0
# dependencies:
#   pre:
#     - brew upgrade
#     - brew update
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
    executor: ruby/default
    steps:
      - checkout
      # - run: brew install pyenv
      - run: 
          name: install python 3.9.6
          command:
              pip install 3.9.6
              # pyenv global 3.9.6
      - run: python3 -m pip install numpy
      - run: python3 -m pip install pandas
      - run: python3 -m pip install sklearn
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
