version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  python: circleci/python@1.4.0
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
    executor: ruby/default
    steps:
      - checkout
      - ruby/bundle-install
      - run: sudo apt-get install python3
      - run: sudo apt-get install python-numpy
      - run: sudo apt-get install python-pandas
      - run: sudo apt-get install python-sklearn
      - run:
          name: Which bundler?
          command: bundle -v
      - run: heroku run rails db:migrate
      - run: bundle exec rspec spec
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: python_config
           
