version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  python: circleci/python@1.4.0
  heroku: circleci/heroku@0.0.10
jobs:
  build:
    working_directory: ~/drink-this-backend
    docker:
      - image: cimg/ruby:2.7.2
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: python3 -m pip install numpy
      - run: python3 -m pip install pandas
      - run: python3 -m pip install sklearn
      - run: bundle install
      - run: bundle exec rspec spec

  # test:
  #   docker:
  #     - image: circleci/ruby:2.7.2
  #   executor: ruby/default
  #   steps:
  #     - checkout
  #     - run: bundle install
  #     # - run: sudo apt-get install python3 python3-dev
  #     # - run: sudo apt-get install python3-pip
  #     # - run: python3 -m pip install numpy
  #     # - run: python3 -m pip install pandas
  #     # - run: python3 -m pip install sklearn
  #     - run: bundle exec rspec spec

workflows:
  heroku_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - test
          filters:
            branches:
              only: python_config

#
# set -e
# buildpack_url=https://github.com/heroku/heroku-buildpack-python
# buildpack_vsn=v197
#
# # rebuild python if it's missing enable-shared
# if  ! python3 -msysconfig | grep enable-shared \
#     > /dev/null; then
#   PYTHON_VERSION="$(< runtime.txt)"
#   git clone -b "$buildpack_vsn" "$buildpack_url" _buildpack
#   export WORKSPACE_DIR="$PWD/_buildpack/builds"
#   rm -f .heroku/python/bin/python   # prevent failing ln after build
#   sed -i 's!figure --pre!figure --enable-shared --pre!' \
#     "$WORKSPACE_DIR"/runtimes/python3
#   "$WORKSPACE_DIR/runtimes/$PYTHON_VERSION" /app/.heroku/python/
#   rm -fr _buildpack
# fi
